core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('player/search/', views.player_search, name='player-search'),
    path('player/<str:username>/', views.player_detail, name='player-detail'),
    path(
        'player/<str:username>/season/<int:season_number>/',
        views.player_detail_by_season,
        name='player-detail-by-season',
    ),
    path('item/list/', views.item_list, name='item-list'),
    path('chart/list/', views.chart_list, name='chart-list'),
]

xp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from xp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('accounts/logout/', auth_views.LogoutView.as_view()),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models


class SeasonManager(models.QuerySet):
    def only_available(self):
        return self.filter(statuses__isnull=False).distinct()

    def last_season(self):
        return self.only_available().last()


class Platform(models.Model):
    epic_id = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=100, unique=True)
    name_long = models.CharField(max_length=100, null=True, blank=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name_long}'


class Season(models.Model):
    name = models.CharField(max_length=100, unique=True)
    number = models.SmallIntegerField(null=True, blank=True, db_index=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    objects = SeasonManager.as_manager()

    def __str__(self):
        return f'{self.name}'

    def save(self, *args, **kwargs):
        if not self.number:
            self.number = ''.join([char for char in self.name if char.isdigit()]) or 0
        super().save(*args, **kwargs)

    class Meta:
        ordering = ('number',)


class Item(models.Model):
    identifier = models.CharField(max_length=100, unique=True, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    upcoming = models.SmallIntegerField(null=True, blank=True)
    cost = models.DecimalField(decimal_places=0, max_digits=9, null=True, blank=True)
    captial = models.CharField(max_length=50, null=True, blank=True)
    type = models.CharField(max_length=50, null=True, blank=True)
    rarity = models.CharField(max_length=50, null=True, blank=True)
    obtained = models.CharField(max_length=50, null=True, blank=True)
    obtained_type = models.CharField(max_length=50, null=True, blank=True)
    featured = models.SmallIntegerField(null=True, blank=True)
    refundable = models.SmallIntegerField(null=True, blank=True)
    ratings = JSONField(null=True, blank=True)
    last_update = models.CharField(max_length=50, null=True, blank=True)
    is_upcoming = models.BooleanField(default=False)

    youtube = models.URLField(null=True, blank=True)
    image = models.URLField(null=True, blank=True)
    image_transparent = models.URLField(null=True, blank=True)
    image_background = models.URLField(null=True, blank=True)
    image_information = models.URLField(null=True, blank=True)
    image_featured_transparent = models.URLField(null=True, blank=True)

    data = JSONField(null=True, blank=True)

    date_added = models.DateTimeField(auto_now_add=True, db_index=True)
    date_changed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Items #{self.id}'

    class Meta:
        ordering = ('-id',)

core/forms.py
from django import forms

from core.models import Platform


class SearchForm(forms.Form):
    username = forms.CharField(required=True, label='')
    platforms = forms.ModelChoiceField(
        queryset=Platform.objects.all(),
        empty_label='selecione a plataforma',
        required=True,
        label='',
        to_field_name='name',
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder': 'digite o usuário'})
        self.fields['username'].widget.attrs.update({'class': 'form-control mr-2'})
        self.fields['platforms'].widget.attrs.update({'class': 'custom-select mr-2'})

core/views.py
from itertools import islice

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from communications.utils import get_profile_data, get_stats_by_season
from core.forms import SearchForm
from core.models import Item, Platform, Season
from core.tasks import get_friends_status, get_items, get_upcoming_items_task
from players.models import Friend, Player


def index(request):
    friends = Friend.objects.all()
    platforms = Platform.objects.all()
    get_friends_status.delay()
    get_upcoming_items_task.delay()
    get_items.delay()
    return render(request, 'core/index.html', {
        'friends': friends,
        'platforms': platforms,
    })


def player_search(request):
    if not request.method == 'POST':
        return render(request, 'core/index.html')
    form = SearchForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        platform = form.cleaned_data['platforms']
        communication = get_profile_data(username, platform)
        if communication.error:
            messages.add_message(
                request,
                messages.ERROR,
                f'Usuário <strong>{username}</strong> não encontrado. '
                'Confira os dados ou selecione outra plataforma.'
            )
            return redirect(request.META.get('HTTP_REFERER'))
        return redirect('core:player-detail', username=communication.player_stats.player.username)


def player_detail(request, username):
    player = get_object_or_404(Player, username=username)
    platform = request.GET.get('platform')
    platforms = [platform.name for platform in player.platforms.all()]
    if platform not in platforms:
        platform = player.last_platform_name
    window_name = request.GET.get('window') or 'alltime'
    try:
        window = Season.objects.get(name=window_name)
    except Season.DoesNotExist:
        window, _ = Season.objects.get_or_create(name='alltime')
    status = player.statuses.filter(
        platform__name=platform, window=window, source='fortnite_tracker'
    ).last()
    seasons = Season.objects.only_available()
    # get_match_history(player.uid)  # TODO: Refactor
    return render(request, 'core/player_detail.html', {
        'player': player,
        'status': status,  # FIXME: Refactor
        'seasons': seasons,
        'season_name': window_name,
    })


def player_detail_by_season(request, username, season_number):
    player = get_object_or_404(Player, username=username)
    platform_name = player.last_platform_name
    try:
        if season_number == 0:
            raise ValueError
        season_name = 'season{number}'.format(number=int(season_number))
    except ValueError:
        return redirect('core:player-detail', username=username)
    window, _ = Season.objects.get_or_create(name=season_name)
    comm = get_stats_by_season(player.id, player.clean_uid, platform_name, window)
    stats = comm.player_stats if comm else None
    seasons = Season.objects.only_available()
    return render(request, 'core/player_detail_by_season.html', {
        'player': player,
        'stats': stats,  # FIXME: Refactor
        'seasons': seasons,
        'season_name': season_name,
    })


@cache_page(0.5 * 60)
def item_list(request):
    items = islice(Item.objects.order_by('?'), 4)
    items_upcoming = Item.objects.filter(is_upcoming=True)
    return render(request, 'core/items_all_list.html', {
        'items': items,
        'items_upcoming': items_upcoming,
    })


@cache_page(3 * 60)
def chart_list(request):
    season_name = request.GET.get('season', 'alltime')
    modes = ['solo', 'duo', 'squad']
    mode = request.GET.get('mode', 'squad').lower()
    if mode not in modes:
        mode = 'squad'
    try:
        season = Season.objects.get(name=season_name)
    except Season.DoesNotExist:
        season, _ = Season.objects.get_or_create(name='alltime')
    friends = Player.objects.filter(friends__isnull=False)
    all_stats = list()
    for friend in friends:
        comm = get_stats_by_season(
            friend.id, friend.clean_uid, friend.last_platform_name, season
        )
        all_stats.append(comm.player_stats if comm else None)
    seasons = Season.objects.only_available()
    return render(request, 'core/chart_list.html', {
        'season_name': season.name,
        'all_stats': all_stats,
        'mode': mode,
        'seasons': seasons,
    })

core/templates/core/base.html
{% load static %}
{% load core_tags %}
{% load i18n %}
{% language 'pt-BR' %}
<!doctype html>
<html lang="pt-br">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    {% block header_imports %}
    {% endblock %}
    <title>Investir != XP</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:chart-list' %}">Gráficos <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:item-list' %}">Itens <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">
                {% block main_title %}
                    Investir não dá XP
                {% endblock %}
            </h1>
            <hr class="my-4">
            {% block main_lead %}
                <p class="lead">
                    encontre suas estatísticas do Fortnite
                </p>
            {% endblock %}
            {% search_form %}
            {% block messages %}
                {% if messages %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {% for message in messages %}
                            {{ message|safe }}
                        {% endfor %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </div>

    {% block content %}
    {% endblock %}

    {% block js %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% block footer_imports %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>
{% endlanguage %}

core/templates/core/items_all_list.html
{% extends 'core/base.html' %}
{% block content %}
    <section class="text-center my-5">
        <h2 class="h1-responsive font-weight-bold text-center my-5">Aleatórios</h2>
        <p class="grey-text text-center w-responsive mx-auto mb-5">Apenas alguns itens aleatórios.</p>
        <div class="container-fluid">
            <div class="row">
                {% for item in items %}
                    <div class="col-lg-3 col-md-6 mb-lg-0 mb-4">
                        <div class="card collection-card z-depth-1-half border-0">
                            <div class="view zoom">
                                <img src="{{ item.image_information }}"
                                     class="img-fluid"
                                     alt="">
                                <div class="stripe dark">
                                    <a>
                                        <p>{{ item.name }}
                                            <i class="fas fa-angle-right"></i>
                                        </p>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section class="text-center my-5">
        <h2 class="h1-responsive font-weight-bold text-center my-5">Próximos</h2>
        <p class="grey-text text-center w-responsive mx-auto mb-5">Lista dos próximos itens a serem disponibilizados.</p>
        <div class="container-fluid">
            <div class="row">
                {% for item in items_upcoming %}
                    <div class="col-lg-2 col-md-4 mb-lg-0 mb-4">
                        <div class="card collection-card z-depth-1-half border-0">
                            <div class="view zoom">
                                <img src="{{ item.image_information }}"
                                     class="img-fluid"
                                     alt="">
                                <div class="stripe dark">
                                    <a>
                                        <p>{{ item.name }}
                                            <i class="fas fa-angle-right"></i>
                                        </p>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

core/templates/core/player_detail.html
{% extends 'core/base.html' %}
{% block main_title %}
    {{ player.username }}
{% endblock %}
{% block search_form %}
{% endblock %}
{% block main_lead %}
    <span><strong>Plataformas:</strong>
    {% for platform in player.platforms.all %}
        <a href="?platform={{ platform.name }}" class="text-dark">{{ platform.name }}</a>{% if not forloop.last %},{% else %}.{% endif %}
    {% endfor %}
    </span>
{% endblock %}
{% block content %}
    <div class="container">
        <p class="text-center">
            {% for season in seasons %}
                <a href="{% url 'core:player-detail-by-season' player.username season.number %}" class="text-dark {% if season_name == season.name %}font-weight-bold{% endif %}">{{ season }}</a> {% if not forloop.last %}|{% endif %}
            {% endfor %}
        </p>
        <div class="mt-2">
            <div class="row">
                <div class="col-xl">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title text-center mb-0">Solos</h3>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Vitórias: <strong>{{ status.stats_solo.top1.value }}</strong></p>
                                    <p class="card-text">Vitórias %: <strong>{{ status.stats_solo.winRatio.value }}</strong></p>
                                    <p class="card-text">Top 10: <strong>{{ status.stats_solo.top10.value }}</strong></p>
                                    <p class="card-text">Top 25: <strong>{{ status.stats_solo.top25.value }}</strong></p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Kills: <strong>{{ status.stats_solo.kills.value }}</strong></p>
                                    <p class="card-text">K/D: <strong>{{ status.stats_solo.kd.value }}</strong></p>
                                    <p class="card-text" style="white-space: nowrap">Pontos: <strong>{{ status.stats_solo.score.value }}</strong></p>
                                    <p class="card-text">PPP: <strong>{{ status.stats_solo.scorePerMatch.value }}</strong></p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Data de atualização: {{ status.date_added|date:'H:i - d/m/y' }}</small>
                        </div>
                    </div>
                </div>

                <div class="col-xl">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title text-center mb-0">Duos</h3>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Vitórias: <strong>{{ status.stats_duo.top1.value }}</strong></p>
                                    <p class="card-text">Vitórias %: <strong>{{ status.stats_duo.winRatio.value }}</strong></p>
                                    <p class="card-text">Top 5: <strong>{{ status.stats_duo.top5.value }}</strong></p>
                                    <p class="card-text">Top 12: <strong>{{ status.stats_duo.top12.value }}</strong></p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Kills: <strong>{{ status.stats_duo.kills.value }}</strong></p>
                                    <p class="card-text">K/D: <strong>{{ status.stats_duo.kd.value }}</strong></p>
                                    <p class="card-text" style="white-space: nowrap">Pontos: <strong>{{ status.stats_duo.score.value }}</strong></p>
                                    <p class="card-text">PPP: <strong>{{ status.stats_duo.scorePerMatch.value }}</strong></p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Data de atualização: {{ status.date_added|date:'H:i - d/m/y' }}</small>
                        </div>
                    </div>
                </div>

                <div class="col-xl">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title text-center mb-0">Squad</h3>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Vitórias: <strong>{{ status.stats_squad.top1.value }}</strong></p>
                                    <p class="card-text">Vitórias %: <strong>{{ status.stats_squad.winRatio.value }}</strong></p>
                                    <p class="card-text">Top 3: <strong>{{ status.stats_squad.top3.value }}</strong></p>
                                    <p class="card-text">Top 6: <strong>{{ status.stats_squad.top6.value }}</strong></p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Kills: <strong>{{ status.stats_squad.kills.value }}</strong></p>
                                    <p class="card-text">K/D: <strong>{{ status.stats_squad.kd.value }}</strong></p>
                                    <p class="card-text" style="white-space: nowrap;">Pontos: <strong>{{ status.stats_squad.score.value }}</strong></p>
                                    <p class="card-text">PPP: <strong>{{ status.stats_squad.scorePerMatch.value }}</strong></p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Data de atualização: {{ status.date_added|date:'H:i - d/m/y' }}</small>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/player_detail_by_season.html
{% extends 'core/base.html' %}
{% block main_title %}
    {{ player.username }}
{% endblock %}
{% block search_form %}
{% endblock %}
{% block main_lead %}
    <span><strong>Plataformas:</strong>
    {% for platform in player.platforms.all %}
        <a href="?platform={{ platform.name }}" class="text-dark">{{ platform.name }}</a>{% if not forloop.last %},{% else %}.{% endif %}
    {% endfor %}
    </span>
{% endblock %}
{% block content %}
    <div class="container">
        <p class="text-center">
            {% for season in seasons %}
                <a href="{% url 'core:player-detail-by-season' player.username season.number %}" class="text-dark {% if season_name == season.name %}font-weight-bold{% endif %}">{{ season }}</a> {% if not forloop.last %}|{% endif %}
            {% endfor %}
        </p>

        <div class="mt-2">
            <div class="row">
                <div class="col-xl">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title text-center mb-0">Solos</h3>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Vitórias: <strong>{{ stats.stats_solo.placetop1_solo }}</strong></p>
                                    <p class="card-text">Vitórias %: <strong>{{ stats.stats_solo.winrate_solo }}</strong></p>
                                    <p class="card-text">Top 10: <strong>{{ stats.stats_solo.placetop10_solo }}</strong></p>
                                    <p class="card-text">Top 25: <strong>{{ stats.stats_solo.placetop25_solo }}</strong></p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Kills: <strong>{{ stats.stats_solo.kills_solo }}</strong></p>
                                    <p class="card-text">K/D: <strong>{{ stats.stats_solo.kd_solo }}</strong></p>
                                    <p class="card-text" style="white-space: nowrap">Pontos: <strong>{{ stats.stats_solo.score_solo }}</strong></p>
                                    <p class="card-text">Partidas: <strong>{{ stats.stats_solo.matchesplayed_solo }}</strong></p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Data de atualização: {{ stats.date_added|date:'H:i - d/m/y' }}</small>
                        </div>
                    </div>
                </div>

                <div class="col-xl">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title text-center mb-0">Duos</h3>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Vitórias: <strong>{{ stats.stats_duo.placetop1_duo }}</strong></p>
                                    <p class="card-text">Vitórias %: <strong>{{ stats.stats_duo.winrate_duo }}</strong></p>
                                    <p class="card-text">Top 5: <strong>{{ stats.stats_duo.placetop5_duo }}</strong></p>
                                    <p class="card-text">Top 12: <strong>{{ stats.stats_duo.placetop12_duo }}</strong></p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Kills: <strong>{{ stats.stats_duo.kills_duo}}</strong></p>
                                    <p class="card-text">K/D: <strong>{{ stats.stats_duo.kd_duo }}</strong></p>
                                    <p class="card-text" style="white-space: nowrap">Pontos: <strong>{{ stats.stats_duo.score_duo }}</strong></p>
                                    <p class="card-text">Partidas: <strong>{{ stats.stats_duo.matchesplayed_duo }}</strong></p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Data de atualização: {{ stats.date_added|date:'H:i - d/m/y' }}</small>
                        </div>
                    </div>
                </div>

                <div class="col-xl">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title text-center mb-0">Squad</h3>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Vitórias: <strong>{{ stats.stats_squad.placetop1_squad }}</strong></p>
                                    <p class="card-text">Vitórias %: <strong>{{ stats.stats_squad.winrate_squad }}</strong></p>
                                    <p class="card-text">Top 3: <strong>{{ stats.stats_squad.placetop3_squad }}</strong></p>
                                    <p class="card-text">Top 6: <strong>{{ stats.stats_squad.placetop6_squad }}</strong></p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card-body">
                                    <p class="card-text">Kills: <strong>{{ stats.stats_squad.kills_squad }}</strong></p>
                                    <p class="card-text">K/D: <strong>{{ stats.stats_squad.kd_squad }}</strong></p>
                                    <p class="card-text" style="white-space: nowrap;">Pontos: <strong>{{ stats.stats_squad.score_squad }}</strong></p>
                                    <p class="card-text">Partidas: <strong>{{ stats.stats_squad.matchesplayed_squad }}</strong></p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Data de atualização: {{ stats.date_added|date:'H:i - d/m/y' }}</small>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}